#!/usr/bin/expect -f


# Check if two arguments are provided
if {[llength $argv] != 2} {
    puts "Usage: $argv0 <SIAB1> <SIAB2>"
    exit 1
}

# Access the arguments
set SIAB1 [lindex $argv 0]
set SIAB2 [lindex $argv 1]



# Spawn a shell
spawn /bin/bash

# Change the working directory to the target directory
send "cd /home/trinity/ctmessaging \r"

expect ".*\\$ $"
send "sudo ./CTMessaging \r"



# Execute a command on the remote computer
expect "*?trinity:*"
send "trinity22!\r"

# Execute a command on the remote computer
expect "*?Hi Operator! Please type your name:*"
send "autoconfig_ctcpu\r"

# Execute a command on the remote computer
expect "CTM>"
send "RemoteControl SMdisable\r"

# Sleep for 5 seconds
sleep 20

# Execute a command on the remote computer
expect "CTM>"
send "SIAB powerHVON -id $SIAB1-$SIAB2\r"

sleep 20


#Execute a command on the remote computer
expect "CTM>"
send "\x04"

# Close the shell
exit
