#!/usr/bin/expect -f


# Spawn a shell
spawn /bin/bash

# Change the working directory to the target directory
send "cd /home/trinity/ctmessaging \r"

expect ".*\\$ $"
send "sudo ./CTMessaging \r"



# Execute a command on the remote computer
expect "*?trinity:*"
send "trinity22!\r"

# Execute a command on the remote computer
expect "*?Hi Operator! Please type your name:*"
send "autoconfig_ctcpu\r"


# Execute a command on the remote computer
expect "CTM>"
send "RemoteControl TriggerScanSF -s 190 -ns 12 -sz 5 -t 2\r"

sleep 200

# Execute a command on the remote computer
expect "CTM>"
send "RemoteControl SMenable\r"

sleep 10

#Execute a command on the remote computer
expect "CTM>"
send "\x04"

# Close the shell
exit
