container_image = rootandexact_buzzard.sif # your container to use
# My very first HTCondor submit file

# Specify your executable (single binary or a script that runs several

#  commands) and arguments to be passed to jobs. 

#  $(Process) will be a integer number for each job, starting with "0"

#  and increasing for the relevant number of jobs.

executable = hello-ospool.sh # name of the bash script or python or root 

arguments = $(Process) # needs to be passed to the script - can be nothing, filename

# Specify the name of the log, standard error, and standard output (or "screen output") files. Wherever you see $(Cluster), HTCondor will insert the 

#  queue number assigned to this set of jobs at the time of submission.

log = hello-ospool_$(Cluster)_$(Process).log # HTCondor log

error = hello-ospool_$(Cluster)_$(Process).err #Standard Error - program and HTCondor errors

output = hello-ospool_$(Cluster)_$(Process).out # program terminal output (not output files)

# This lines *would* be used if there were any other filesr the executable to use.

transfer_input_files = file1,/absolute/pathto/file2,etc #any file that needs to included for the job - everything minus executable
# HTCondor will transfer the executable
# Examples
# Containers (.sif)
# Datafiles
# input files
# references (mappings)
# add in comma seperation

# Specify Job duration category as "Medium" (expected runtime <10 hr) or "Long" (expected runtime <20 hr). 

#+JobDurationCategory = "Medium"
# OSpool match jobs by length -- long jobs go to faster hardware
# Tell HTCondor requirements (e.g., operating system) your job needs, 

# what amount of compute resources each job will need on the computer where it runs.

#requirements = (OSGVO_OS_STRING == "RHEL 9")
# jobs need on redhat specific version (os, also be architeture/hardware things no us)

# resources requests
# these jobs will only run on 1 node
# multi node is not possible (independent jobs)

request_cpus = 1 # these are PER JOB

request_memory = 1GB # these are PER JOB

# space for all files input and output and intermediate files
request_disk = 5GB # these are PER JOB

# Tell HTCondor to run 3 instances of our job:
###----------#####
# Queue! HAS TO BE THE LAST LINE
###----------#####
# MAGICAL
# synatax 
# queue + num - que this many identical jobs (EXACT  SAME JOB)
# use case - executable can create independent jobs (script creates difference between jobs)
# randomw number simulations 
queue 3
 

