#!/usr/bin/expect -f


# Check if two arguments are provided
if {[llength $argv] != 3} {
    puts "Usage: $argv0 <th> <s1> <s2>"
    exit 1
}

# Access the arguments
set th [lindex $argv 0]
set s1 [lindex $argv 1]
set s2 [lindex $argv 2]



# Spawn a shell
spawn /bin/bash

# Change the working directory to the target directory
send "cd /home/trinity/ctmessaging \r"

expect ".*\\$ $"
send "sudo ./CTMessaging \r"


# Execute a command on the remote computer
expect "*?trinity:*"
send "trinity22!\r"

# Execute a command on the remote computer
expect "*?Hi Operator! Please type your name:*"
send "autopixelthreshold_ctcpu\r"

# Execute a command on the remote computer
expect "CTM>"
send "RemoteControl SMdisable\r"

sleep 10


# Execute a command on the remote computer
expect "CTM>"
send "SIAB MusicConfTrigTh -m both -th $th -id $s1-$s2\r"

sleep 20

#Execute a command on the remote computer
expect "CTM>"
send "\x04"

# Close the shell
exit
