#!/usr/bin/expect -f


# Read in the IP address, username, and password from the file
set file "/data/TrinityLabComputer/control_comp/pass_ctcpu.txt"
set fh [open $file r]
gets $fh ip
gets $fh user
gets $fh password
close $fh

set remote_directory "/home/trinity/Documents/Data/"

# Generate the current date on the local machine
set current_date [exec date --utc "+%Y%m%d"]

# Connect to the remote computer using SSH
spawn ssh $user@$ip

# Wait for the password prompt and send the password
expect "password:"
send "$password\r"

# Execute a command on the remote computer
expect "trinity@trinityCPU:~$#"
send "cd $remote_directory$current_date/RawDataMerged \r"
#send "cd $remote_directory/20231107/RawDataMerged \r"

# get number of files
expect "trinity@trinityCPU:~/RawDataMerged$"
send "ls -1 | wc -l \r"

# gets last file name
expect "trinity@trinityCPU:~/RawDataMerged$"
send "ls -t | head -n1 \r"

# gets last files size
expect "trinity@trinityCPU:~/RawDataMerged$"
send "stat --printf=\"%s\" \"\$(ls -t | head -n1)\"\r"

# Wait for the command prompt again
expect "trinity@trinityCPU:~/RawDataMerged$"
send "exit\r"

# Wait for the SSH session to close
expect eof


# Execute a command on the remote computer
#expect "trinity@trinityCPU:~/ctmessaging$"
#send "sudo ./CTMessaging\r"






# Wait for the command to finish and exit
#expect "trinity@trinityCPU:~/ctmessaging$"
#send "exit\r"



